defaults: &defaults
  access_key_id: <%= ENV['amazonaccesskey'] %>
  secret_access_key: <%= ENV['amazonsecretkey'] %>
  bucket: <%= ENV['amazonbucket'] %>
  max_file_size: 524288000 # 500 megabytes

development:
  <<: *defaults
    
test:
  <<: *defaults
  
production:
  <<: *defaults
