defaults: &defaults
  googleclientid: {GOOGLE_CLIENT_ID}
  googleclientsecret: {GOOGLE_CLIENT_SECRET}
  apikey: {API_KEY}
  almaurl: https://api-na.hosted.exlibrisgroup.com/almaws/v1
  paypalurl: https://api.sandbox.paypal.com/v1
  paypayclientid: {PAYPAL_CLIENT_ID}
  paypalsecret: {PAYPAL_SECRET}
  amazonaccesskey: {AMAZON_ACCESS_KEY}
  amazonsecretkey: {AMAZON_SECRET_KEY}
  amazonbucket: {AMAZON_BUCKET}
  institution: {INSTITUTION_CODE}

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults