defaults: &defaults
  googleclientid: {GOOGLE_CLIENT_ID}
  googleclientsecret: {GOOGLE_CLIENT_SECRET}
  apikey: {API_KEY}
  almaurl: https://api-na.hosted.exlibrisgroup.com/almaws/v1
  paypalurl: https://api.sandbox.paypal.com/v1
  paypayclientid: {PAYPAL_CLIENT_ID}
  paypalsecret: {PAYPAL_SECRET}
  pdsurl: {PDS URL}
  institution: {Alma Institution}
  domain: {AWS Cloud Search domain}
  amazonscratchbucket: {AWS S3 scratch bucket}
  oaiset: {OAI set}
  alma: {Alma instance name}

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults