defaults: &defaults
  googleclientid: {GOOGLE_CLIENT_ID}
  googleclientsecret: {GOOGLE_CLIENT_SECRET}
  apikey: {API_KEY}
  almaurl: https://api-na.hosted.exlibrisgroup.com/almaws/v1
  paypalurl: https://api.sandbox.paypal.com/v1
  paypayclientid: {PAYPAL_CLIENT_ID}
  paypalsecret: {PAYPAL_SECRET}
  pdsurl: {PDS URL}
  catalog_amazonaccesskey: {AMAZON_ACCESS_KEY}
  catalog_amazonsecretkey: {AMAZON_SECRET_KEY}
  digital_amazonaccesskey: {AMAZON_ACCESS_KEY}
  digital_amazonsecretkey: {AMAZON_SECRET_KEY}
  amazonbucket: {AMAZON_BUCKET}
  amazonregion: us-east-1
  institution: {Alma Institution}
  domain: {AWS Cloud Search domain}
  oaiset: {OAI set}
  alma: {Alma instance name}

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults